In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("complete_site_info.xlsx")
print(df.columns)
df.head()

Index(['Model_number', 'Date', 'Site_Name', 'Israelis_Count', 'Tourists_Count',
       'Total', 'region_Central', 'region_Judea_Samaria', 'region_North',
       'region_South', 'is_weekend', 'operations', 'is_jewish_holiday',
       'is_jewish_vacation', 'is_muslims_holiday', 'is_muslims_vacation',
       'camping', 'special_activity', 'visit_duration', 'jewish', 'muslims',
       'christians', 'national park', 'nature reserve', 'archaeology',
       'religion', 'animals', 'heritage', 'water', 'cave', 'lookout', 'pm10',
       'pm2.5', 'nox', 'so2', 'Temperature', 'is_HeatWave',
       'Tel_Aviv-Yafo_pm10', 'Jerusalem_pm10', 'Haifa_pm10', 'Ashkelon_pm10',
       'Beer-Sheva_pm10', 'Eilat_pm10', 'Qiryat Shemona_pm10', 'Safed_pm10',
       'Tel_Aviv-Yafo_pm2.5', 'Jerusalem_pm2.5', 'Haifa_pm2.5',
       'Ashkelon_pm2.5', 'Beer-Sheva_pm2.5', 'Eilat_pm2.5',
       'Qiryat Shemona_pm2.5', 'Safed_pm2.5', 'Tel_Aviv-Yafo_nox',
       'Jerusalem_nox', 'Haifa_nox', 'Ashkelon_nox', 'Beer-Sheva_nox',
       'Eilat_nox', 'Qiryat Shemona_nox', 'Safed_nox', 'Tel_Aviv-Yafo_so2',
       'Jerusalem_so2', 'Haifa_so2', 'Ashkelon_so2', 'Beer-Sheva_so2',
       'Eilat_so2', 'Qiryat Shemona_so2', 'Safed_so2'],
      dtype='object')

,Model_number,Date,Site_Name,Israelis_Count,Tourists_Count,Total,region_Central,region_Judea_Samaria,region_North,region_South,...,Qiryat Shemona_nox,Safed_nox,Tel_Aviv-Yafo_so2,Jerusalem_so2,Haifa_so2,Ashkelon_so2,Beer-Sheva_so2,Eilat_so2,Qiryat Shemona_so2,Safed_so2
0,3,2016-06-11,The Majrase – Betiha,1269,25,1294,0,0,1,0,...,26.8,26.8,9.2,0.200000,10.5,1.6,2.9,0.850000,3.9,3.9
1,3,2016-02-08,Amud Stream,13,0,13,0,0,1,0,...,9.4,9.4,7.4,0.300000,1.3,1.3,1.7,1.466667,0.6,0.6
2,5,2016-04-07,Kokhav HaYarden,163,18,181,0,0,1,0,...,6.8,6.8,3.9,0.100000,1.5,0.6,0.7,1.300000,0.6,0.6
3,5,2016-04-08,Khan Be’erot,215,0,215,0,0,0,1,...,8.2,8.2,8.2,1.366667,2.9,6.3,8.0,1.200000,0.6,0.6
4,0,2016-04-29,En Gedi,4723,637,5360,0,0,0,1,...,5.9,5.9,6.0,2.250000,4.3,1.0,4.4,0.300000,0.8,0.8

In [3]:
#setting all the default parameters like empty columns, thresholds etc.
pm10_threshold = 130
pm25_threshold = 37.5
nox_threshold = 25
so2_threshold = 50
df['is_Site_exceeded_pm10']=0
df['is_Site_exceeded_pm2.5']=0
df['is_Site_exceeded_nox']=0
df['is_Site_exceeded_so2']=0
df['is_Site_exceeded_pm10'][df['pm10']>pm10_threshold]=1
df['is_Site_exceeded_pm2.5'][df['pm2.5']>pm25_threshold]=1
df['is_Site_exceeded_so2'][df['so2']>=nox_threshold]=1
df['is_Site_exceeded_nox'][df['nox']>=so2_threshold]=1

print("pm10 |", df["Date"][df['is_Site_exceeded_pm10']==1].count(),"|",df["Date"][df['is_Site_exceeded_pm10']==1].count()/len(df))
print("pm2.5|",df["Date"][df['is_Site_exceeded_pm2.5']==1].count(),"|",df["Date"][df['is_Site_exceeded_pm2.5']==1].count()/len(df))
print("nox|",  df["Date"][df['is_Site_exceeded_nox']==1].count(),"|",df["Date"][df['is_Site_exceeded_nox']==1].count()/len(df))
print("so2|" , df["Date"][df['is_Site_exceeded_so2']==1].count(),"|",df["Date"][df['is_Site_exceeded_so2']==1].count()/len(df))
print("------------------------------------------------------------")

pm10 | 9714 | 0.08903105180188438
pm2.5| 11236 | 0.1029805330498222
nox| 15939 | 0.14608461341056567
so2| 53 | 0.00048575723136708583
------------------------------------------------------------

C:\Users\liavc\AppData\Local\Temp/ipykernel_11056/4155842654.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['is_Site_exceeded_pm10'][df['pm10']>pm10_threshold]=1
C:\Users\liavc\AppData\Local\Temp/ipykernel_11056/4155842654.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['is_Site_exceeded_pm2.5'][df['pm2.5']>pm25_threshold]=1
C:\Users\liavc\AppData\Local\Temp/ipykernel_11056/4155842654.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['is_Site_exceeded_so2'][df['so2']>=nox_threshold]=1
C:\Users\liavc\AppData\Local\Temp/ipykernel_11056/4155842654.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['is_Site_exceeded_nox'][df['nox']>=so2_threshold]=1

In [4]:
pm10_city_list=['Tel_Aviv-Yafo_pm10', 'Jerusalem_pm10', 'Haifa_pm10', 'Ashkelon_pm10','Beer-Sheva_pm10', 'Eilat_pm10', 'Qiryat Shemona_pm10', 'Safed_pm10']
pm25_city_list=['Tel_Aviv-Yafo_pm2.5', 'Jerusalem_pm2.5', 'Haifa_pm2.5','Ashkelon_pm2.5', 'Beer-Sheva_pm2.5', 'Eilat_pm2.5','Qiryat Shemona_pm2.5', 'Safed_pm2.5']
nox_city_list=['Tel_Aviv-Yafo_nox','Jerusalem_nox', 'Haifa_nox', 'Ashkelon_nox', 'Beer-Sheva_nox','Eilat_nox', 'Qiryat Shemona_nox', 'Safed_nox']
so2_city_list=[ 'Tel_Aviv-Yafo_so2','Jerusalem_so2', 'Haifa_so2', 'Ashkelon_so2', 'Beer-Sheva_so2','Eilat_so2', 'Qiryat Shemona_so2', 'Safed_so2']

In [5]:
(((df[pm10_city_list]>pm10_threshold).sum(axis=1))>=1)
(((df[pm25_city_list]>pm25_threshold).sum(axis=1))>=1)
(((df[so2_city_list]>so2_threshold).sum(axis=1)  )>=1)
(((df[nox_city_list]>nox_threshold).sum(axis=1)  )>=1)

0         True
1         True
2         True
3         True
4         True
          ...
109103    True
109104    True
109105    True
109106    True
109107    True
Length: 109108, dtype: bool

In [9]:
#if a pollutant exceeded 
def f1(type_threshold,listType):
    for c in listType:
        a = [ 1 if x else 0 for x in (df[c]>type_threshold) ]
        name = c+'_exceeded'
        df.insert(len(df.columns),name,a)

In [10]:
pd.set_option("display.max_columns", None)
df.head()

,Model_number,Date,Site_Name,Israelis_Count,Tourists_Count,Total,region_Central,region_Judea_Samaria,region_North,region_South,is_weekend,operations,is_jewish_holiday,is_jewish_vacation,is_muslims_holiday,is_muslims_vacation,camping,special_activity,visit_duration,jewish,muslims,christians,national park,nature reserve,archaeology,religion,animals,heritage,water,cave,lookout,pm10,pm2.5,nox,so2,Temperature,is_HeatWave,Tel_Aviv-Yafo_pm10,Jerusalem_pm10,Haifa_pm10,Ashkelon_pm10,Beer-Sheva_pm10,Eilat_pm10,Qiryat Shemona_pm10,Safed_pm10,Tel_Aviv-Yafo_pm2.5,Jerusalem_pm2.5,Haifa_pm2.5,Ashkelon_pm2.5,Beer-Sheva_pm2.5,Eilat_pm2.5,Qiryat Shemona_pm2.5,Safed_pm2.5,Tel_Aviv-Yafo_nox,Jerusalem_nox,Haifa_nox,Ashkelon_nox,Beer-Sheva_nox,Eilat_nox,Qiryat Shemona_nox,Safed_nox,Tel_Aviv-Yafo_so2,Jerusalem_so2,Haifa_so2,Ashkelon_so2,Beer-Sheva_so2,Eilat_so2,Qiryat Shemona_so2,Safed_so2,is_Site_exceeded_pm10,is_Site_exceeded_pm2.5,is_Site_exceeded_nox,is_Site_exceeded_so2
0,3,2016-06-11,The Majrase – Betiha,1269,25,1294,0,0,1,0,1,0,1,0,0,0,0,0,2,0,0,0,0,1,0,0,0,0,1,0,0,NaN,0.6,0.0,19.77,24.2,0,110.9,201.1,49.7,18.3,48.95,26.4,26.4,26.4,48.4,34.0,75.7,10.1,10.9,10.9,20.10,20.10,407.4,854.9,470.1,6.6,54.3,15.2,26.8,26.8,9.2,0.200000,10.5,1.6,2.9,0.850000,3.9,3.9,0,0,0,0
1,3,2016-02-08,Amud Stream,13,0,13,0,0,1,0,0,0,0,0,0,0,1,0,3,0,0,0,0,1,0,0,0,0,1,0,0,NaN,0.1,0.0,19.72,15.1,0,86.2,320.1,73.9,45.3,49.90,54.4,54.4,54.4,49.5,75.6,96.1,28.2,25.7,25.7,18.15,18.15,77.8,1210.8,157.7,8.3,39.3,10.1,9.4,9.4,7.4,0.300000,1.3,1.3,1.7,1.466667,0.6,0.6,0,0,0,0
2,5,2016-04-07,Kokhav HaYarden,163,18,181,0,0,1,0,0,0,0,0,0,1,1,1,2,0,0,1,1,0,1,0,0,0,0,0,1,NaN,NaN,0.0,19.37,19.8,0,105.6,71.5,61.4,41.6,37.80,38.7,38.7,38.7,32.4,55.4,57.9,42.1,16.4,16.4,20.90,20.90,133.7,1168.5,39.4,1.5,10.4,2.5,6.8,6.8,3.9,0.100000,1.5,0.6,0.7,1.300000,0.6,0.6,0,0,0,0
3,5,2016-04-08,Khan Be’erot,215,0,215,0,0,0,1,1,0,0,0,0,1,1,0,5,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0.6,0.0,18.04,25.4,0,117.5,97.6,76.0,48.6,52.10,58.3,58.3,58.3,68.8,85.1,111.8,30.6,29.2,29.2,28.20,28.20,94.8,1513.3,134.3,8.1,25.0,5.7,8.2,8.2,8.2,1.366667,2.9,6.3,8.0,1.200000,0.6,0.6,0,0,0,0
4,0,2016-04-29,En Gedi,4723,637,5360,0,0,0,1,1,0,1,0,0,0,0,1,4,1,0,0,0,1,1,0,0,0,1,0,0,28.0,NaN,0.0,16.70,20.9,0,74.1,86.7,45.1,18.5,25.30,33.2,33.2,33.2,30.2,33.5,54.2,21.4,12.8,12.8,12.10,12.10,70.3,30.5,75.5,1.2,15.6,4.8,5.9,5.9,6.0,2.250000,4.3,1.0,4.4,0.300000,0.8,0.8,0,0,0,0

In [11]:
f1(pm10_threshold,pm10_city_list)
f1(pm25_threshold,pm25_city_list)
f1(so2_threshold,so2_city_list)
f1(nox_threshold,nox_city_list)
df.head()

,Model_number,Date,Site_Name,Israelis_Count,Tourists_Count,Total,region_Central,region_Judea_Samaria,region_North,region_South,is_weekend,operations,is_jewish_holiday,is_jewish_vacation,is_muslims_holiday,is_muslims_vacation,camping,special_activity,visit_duration,jewish,muslims,christians,national park,nature reserve,archaeology,religion,animals,heritage,water,cave,lookout,pm10,pm2.5,nox,so2,Temperature,is_HeatWave,Tel_Aviv-Yafo_pm10,Jerusalem_pm10,Haifa_pm10,Ashkelon_pm10,Beer-Sheva_pm10,Eilat_pm10,Qiryat Shemona_pm10,Safed_pm10,Tel_Aviv-Yafo_pm2.5,Jerusalem_pm2.5,Haifa_pm2.5,Ashkelon_pm2.5,Beer-Sheva_pm2.5,Eilat_pm2.5,Qiryat Shemona_pm2.5,Safed_pm2.5,Tel_Aviv-Yafo_nox,Jerusalem_nox,Haifa_nox,Ashkelon_nox,Beer-Sheva_nox,Eilat_nox,Qiryat Shemona_nox,Safed_nox,Tel_Aviv-Yafo_so2,Jerusalem_so2,Haifa_so2,Ashkelon_so2,Beer-Sheva_so2,Eilat_so2,Qiryat Shemona_so2,Safed_so2,is_Site_exceeded_pm10,is_Site_exceeded_pm2.5,is_Site_exceeded_nox,is_Site_exceeded_so2,Tel_Aviv-Yafo_pm10_exceeded,Jerusalem_pm10_exceeded,Haifa_pm10_exceeded,Ashkelon_pm10_exceeded,Beer-Sheva_pm10_exceeded,Eilat_pm10_exceeded,Qiryat Shemona_pm10_exceeded,Safed_pm10_exceeded,Tel_Aviv-Yafo_pm2.5_exceeded,Jerusalem_pm2.5_exceeded,Haifa_pm2.5_exceeded,Ashkelon_pm2.5_exceeded,Beer-Sheva_pm2.5_exceeded,Eilat_pm2.5_exceeded,Qiryat Shemona_pm2.5_exceeded,Safed_pm2.5_exceeded,Tel_Aviv-Yafo_so2_exceeded,Jerusalem_so2_exceeded,Haifa_so2_exceeded,Ashkelon_so2_exceeded,Beer-Sheva_so2_exceeded,Eilat_so2_exceeded,Qiryat Shemona_so2_exceeded,Safed_so2_exceeded,Tel_Aviv-Yafo_nox_exceeded,Jerusalem_nox_exceeded,Haifa_nox_exceeded,Ashkelon_nox_exceeded,Beer-Sheva_nox_exceeded,Eilat_nox_exceeded,Qiryat Shemona_nox_exceeded,Safed_nox_exceeded
0,3,2016-06-11,The Majrase – Betiha,1269,25,1294,0,0,1,0,1,0,1,0,0,0,0,0,2,0,0,0,0,1,0,0,0,0,1,0,0,NaN,0.6,0.0,19.77,24.2,0,110.9,201.1,49.7,18.3,48.95,26.4,26.4,26.4,48.4,34.0,75.7,10.1,10.9,10.9,20.10,20.10,407.4,854.9,470.1,6.6,54.3,15.2,26.8,26.8,9.2,0.200000,10.5,1.6,2.9,0.850000,3.9,3.9,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,1,1
1,3,2016-02-08,Amud Stream,13,0,13,0,0,1,0,0,0,0,0,0,0,1,0,3,0,0,0,0,1,0,0,0,0,1,0,0,NaN,0.1,0.0,19.72,15.1,0,86.2,320.1,73.9,45.3,49.90,54.4,54.4,54.4,49.5,75.6,96.1,28.2,25.7,25.7,18.15,18.15,77.8,1210.8,157.7,8.3,39.3,10.1,9.4,9.4,7.4,0.300000,1.3,1.3,1.7,1.466667,0.6,0.6,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0
2,5,2016-04-07,Kokhav HaYarden,163,18,181,0,0,1,0,0,0,0,0,0,1,1,1,2,0,0,1,1,0,1,0,0,0,0,0,1,NaN,NaN,0.0,19.37,19.8,0,105.6,71.5,61.4,41.6,37.80,38.7,38.7,38.7,32.4,55.4,57.9,42.1,16.4,16.4,20.90,20.90,133.7,1168.5,39.4,1.5,10.4,2.5,6.8,6.8,3.9,0.100000,1.5,0.6,0.7,1.300000,0.6,0.6,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0
3,5,2016-04-08,Khan Be’erot,215,0,215,0,0,0,1,1,0,0,0,0,1,1,0,5,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0.6,0.0,18.04,25.4,0,117.5,97.6,76.0,48.6,52.10,58.3,58.3,58.3,68.8,85.1,111.8,30.6,29.2,29.2,28.20,28.20,94.8,1513.3,134.3,8.1,25.0,5.7,8.2,8.2,8.2,1.366667,2.9,6.3,8.0,1.200000,0.6,0.6,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0
4,0,2016-04-29,En Gedi,4723,637,5360,0,0,0,1,1,0,1,0,0,0,0,1,4,1,0,0,0,1,1,0,0,0,1,0,0,28.0,NaN,0.0,16.70,20.9,0,74.1,86.7,45.1,18.5,25.30,33.2,33.2,33.2,30.2,33.5,54.2,21.4,12.8,12.8,12.10,12.10,70.3,30.5,75.5,1.2,15.6,4.8,5.9,5.9,6.0,2.250000,4.3,1.0,4.4,0.300000,0.8,0.8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0

In [12]:
df.to_excel("site_info_ver_2.0.xlsx")